### ISSUE TITLE
Feature: Recipe Page

### ISSUE THREAD

**Issue by GktgYildiz** [Fridgefy/fridgefy#10]
### Type of feature

🚀 Feature

### Description

Create the Recipe Page

<img width="792" alt="Screenshot 2023-12-06 at 2 12 50 PM" src="https://github.com/Fridgefy/fridgefy/assets/102765970/14124d4d-383c-4a8c-9d29-8015816829f2">

### Tasks

- [x] Create basic layout
- [x] Create sidebar for My Fridge
- [x] Create sidebar for My Recipes
- [x] Create Filters 
- [x] Create Recipe Cards

**Comment by GktgYildiz** [comment]
here is how it look like now! without actions and logic 
<img width="1440" alt="Screenshot 2023-12-07 at 3 42 37 AM" src="https://github.com/Fridgefy/fridgefy/assets/102765970/27d9c6dc-8e61-42b0-93b7-b74e7fbb728d">
